name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4.2.2

    - name: Set up Java Development Kit
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Gradle Environment
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.3.1'

    - name: Generate Dummy Keystore and Build APK
      run: |
        keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        gradle assembleDebug -Pandroid.injected.signing.store.file="debug.keystore" -Pandroid.injected.signing.store.password="android" -Pandroid.injected.signing.key.alias="androiddebugkey" -Pandroid.injected.signing.key.password="android"



    - name: Upload Finished APK
      uses: actions/upload-artifact@v4.5.0
      with:
        name: game-apk
        path: app/build/outputs/apk/debug/app-debug.apk
